title: DFT Algos
description: Exposé of popular DFT algorithms
show_downloads: true
theme: jekyll-theme-slate
remote_theme: pages-themes/slate@v0.2.0
show_downloads: "false"
plugins:
- jekyll-remote-theme

