title: DFT Algos
logo: /assets/img/logo.png
description: An educational repository for algorithms related to the Discrete Fourier Transform
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
